### ISSUE TITLE
[Feature] Add the ability to change the number of pages per sheet

### ISSUE THREAD

**Issue by Doldrums** [Drop-Team/InnoPrintBot#6]
Hey, folks
firstly, thanks for what you are doing
But it would be cool to have the ability to change the number of pages per sheet. Suppose I have a very large document and would like to spend less paper while optimizing print quality
<img width="594" alt="Screenshot 2021-11-15 at 02 04 09" src="https://user-images.githubusercontent.com/38398999/141702261-003d28d1-9e9f-4990-9bea-9dcc9e0ac750.png">

**Comment by KeepError** [comment]
Released
